name: ClubTools Web API CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ClubTools.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clubtools-api:latest
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - name: Deploy to Azure Web App
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'your-api-app-name'
#         slot-name: 'production'
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         images: 'DOCKER|${{ secrets.DOCKER_USERNAME }}/clubtools-api:latest'
