name: ClubTools Website CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Build
        run: dotnet build ./src/ClubTools.Website/ClubTools.Website.csproj --configuration Release

      - name: Publish
        run: dotnet publish ./src/ClubTools.Website/ClubTools.Website.csproj --configuration Release --output ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clubtools-website
          path: ./publish
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - name: Download artifact
#       uses: actions/download-artifact@v2
#       with:
#         name: blazor-wasm
#         path: ./publish

#     - name: Deploy to Azure Static Web Apps
#       uses: Azure/static-web-apps-deploy@v1
#       with:
#         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
#         action: "upload"
#         app_location: "/"
#         output_location: "wwwroot"
